<?php
/**
 * Copyright © 2016 SW-THEMES. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Smartwave\Megamenu\Helper\Data');
    $_config = $_helper->getConfig('sw_megamenu');
    $columnsLimit = 0;
    $header_type = $_helper->getConfig('porto_settings/header/header_type');
    
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation sw-megamenu <?php if($header_type == 8 || $header_type == 10): ?>side-megamenu<?php endif; ?>" role="navigation">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
    });
</script>
<?php
    } else {
?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>

<?php
    }
?>
<style>
    .sw-megamenu.navigation li.level0:first-child,
    .sw-megamenu.navigation li.level0:last-child{
        display: none!important;
    }
    .sw-megamenu.navigation > ul{display: table;}
    .sw-megamenu.navigation li.level0.fullwidth{display: table-cell; vertical-align: middle;}
    .navigation .level0 > .level-top{line-height: 16px; padding: 12px;}
    .page-header.type2 .navigation .level0.parent > a:after{line-height: 16px;}
    .page-header .navigation .level0.parent > a:after{position: absolute; display: none;}
    header.page-header.sticky-header .navigation li.level0 > .level-top{line-height: 16px;}
    
</style>
